# Generated by Django 4.2.3 on 2023-08-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.TextField(max_length=70)),
            ],
        ),
    ]
