# Generated by Django 4.2.3 on 2023-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=70),
        ),
    ]
